import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..');

function extractRoutes(source) {
  const routes = new Set();
  const literal = /url\.pathname\s*(?:===|!==)\s*['"]([^'"]+)['"]/g;
  const startsWith = /url\.pathname\.startsWith\(['"]([^'"]+)['"]\)/g;
  const endsWith = /url\.pathname\.endsWith\(['"]([^'"]+)['"]\)/g;
  for (const regex of [literal, startsWith, endsWith]) {
    for (const match of source.matchAll(regex)) {
      routes.add(match[1]);
    }
  }
  return [...routes].filter((route) => route !== '/api/' && route !== '/api').sort();
}

async function main() {
  const nodeSource = await fs.readFile(path.join(repoRoot, 'packages/runtime-node/src/index.ts'), 'utf-8');
  const workerSource = await fs.readFile(path.join(repoRoot, 'packages/runtime-cloudflare/src/index.ts'), 'utf-8');
  const durableObjectSource = await fs.readFile(path.join(repoRoot, 'packages/runtime-cloudflare/src/agent-do.ts'), 'utf-8');

  const nodeRoutes = extractRoutes(nodeSource);
  const workerRoutes = new Set([...extractRoutes(workerSource), ...extractRoutes(durableObjectSource)]);
  const rows = nodeRoutes
    .filter((route) => route.startsWith('/api/') || route.startsWith('/.') || route.startsWith('/health'))
    .map((route) => ({
      route,
      cloudflare: workerRoutes.has(route) || [...workerRoutes].some((candidate) => candidate.length > 6 && route.startsWith(candidate)),
    }));

  const markdown = [
    '# Cloudflare Route Parity',
    '',
    'Generated by `node scripts/audit-routes.mjs`.',
    '',
    '| Node route | Cloudflare coverage |',
    '| --- | --- |',
    ...rows.map((row) => `| \`${row.route}\` | ${row.cloudflare ? 'covered' : 'missing'} |`),
    '',
  ].join('\n');

  await fs.writeFile(path.join(repoRoot, 'docs/cloudflare-route-parity.md'), markdown, 'utf-8');
  console.log(markdown);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
